### ISSUE TITLE
Content Version health check issue

### ISSUE THREAD

**Issue by NikRimington** [prjseal/Our.Umbraco.HealthChecks#27]
I believe there might be an issue with the Content Version health check.

Using the following clean setup: 
Umbraco 7.13.2
SQL CE
Starter Kit
UnVersion
Health Check package

Running the data integrity health check group is throwing the following error:

```
An error occured
Value cannot be null.
 Parameter name: connection

Exception Details
System.ArgumentNullException: Value cannot be null.
 Parameter name: connection
```

Stack trace:
```
Stacktrace
at StackExchange.Profiling.Data.ProfiledDbConnection..ctor(DbConnection connection, IDbProfiler profiler) in c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbConnection.cs:line 59
   at Umbraco.Core.Persistence.UmbracoDatabase.OnConnectionOpened(IDbConnection connection)
   at Umbraco.Core.Persistence.Database.OpenSharedConnection()
   at Umbraco.Core.Persistence.Database.ExecuteScalar[T](String sql, Object[] args)
   at Our.Umbraco.HealthChecks.Checks.DataIntegrity.ContentVersionsCheck.TotalNumberOfVersions()
   at Our.Umbraco.HealthChecks.Checks.DataIntegrity.ContentVersionsCheck.CheckTotalNumberOfVersions(Boolean IsUnversionInstalled, Int32 warningLevelOfVersions)
   at Our.Umbraco.HealthChecks.Checks.DataIntegrity.ContentVersionsCheck.GetStatus()
   at Umbraco.Web.HealthCheck.HealthCheckController.GetStatus(Guid id)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
```

Is there a reason that SQL syntax isn't being taken into account when performing the querying [not that I think it is related]?

**Comment by joecklau** [comment]
Facing same problem
